![header-notebooks.png]()

Esta é a tarefa proposta para a **Aula 6: Tratamento com MinIO e MongoDB**, do curso de **Engenharia de Dados** da **[Awari](https://awari.com.br/)**.

---

# O que fazer?
##### Com base no que foi visto em aula e com base nos dados e arquivos tratados na 5ª aula (aula anterior), a atividade consiste, sempre no workspace em Docker, em:

1. Criar script para ler os datasets em /exercicios/municipios-estados/csv — o script deve:
    1. Criar uma pasta nomeada com a sigla da UF para cada estado encontrado no arquivo JSON;
    2. Organizar as cidades por estado um único arquivo CSV, nomeado como cidades.csv;
    3. Salvar esse arquivo cidades.csv dentro da pasta da UF (estado) correspondente.
2. Importar as pastas e arquivos salvos para um bucket no MinIO.
3. Exportar os dados para o MongoDB e visualizá-los a partir do banco de dados.

# Instalando bibliotecas

In [1]:
!pip install pandas
!pip install pymongo
!pip install boto3

Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: pymongo in /opt/conda/lib/python3.10/site-packages (4.4.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /opt/conda/lib/python3.10/site-packages (from pymongo) (2.3.0)
Requirement already satisfied: boto3 in /opt/conda/lib/python3.10/site-packages (1.26.160)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from boto3) (0.6.1)
Requirement already satisfied: botocore<1.30.0,>=1.29.160 in /opt/conda/lib/python3.10/site-packages (from boto3) (1.29.160)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from boto3) (1.0.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/conda/lib/python3.10/site-packages (from botocore<1.30.0,>=1.29.160->boto3) (1.26.14)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.10/site-packages (from botocore<1.30.0,>=1.29.160->boto3) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.30.0,>=1.29.160->boto3) (1.16.0)

# Importando bibliotecas

In [2]:
import numpy as np
import pandas as pd
from io import BytesIO
from pymongo import MongoClient
import boto3
from io import StringIO

## Criando um script para ler os datasets em /exercicios/municipios-estados/csv

In [6]:
dfEstados = pd.read_csv('./arquivos/municipios-estados/csv/estados.csv')
dfEstados.head()

   codigo_uf  uf      nome  latitude  longitude regiao
0         11  RO  Rondônia    -10.83     -63.34  Norte
1         12  AC      Acre     -8.77     -70.55  Norte
2         13  AM  Amazonas     -3.47     -65.10  Norte
3         14  RR   Roraima      1.99     -61.33  Norte
4         15  PA      Pará     -3.79     -52.48  Norte

In [7]:
dfMunicipios = pd.read_csv('./arquivos/municipios-estados/csv/municipios.csv')
dfMunicipios.head()

,codigo_ibge,nome,latitude,longitude,capital,codigo_uf,siafi_id,ddd,fuso_horario
0,5200050,Abadia de Goiás,-16.75730,-49.4412,0,52,1050,62,America/Sao_Paulo
1,3100104,Abadia dos Dourados,-18.48310,-47.3916,0,31,4001,34,America/Sao_Paulo
2,5200100,Abadiânia,-16.19700,-48.7057,0,52,9201,62,America/Sao_Paulo
3,3100203,Abaeté,-19.15510,-45.4444,0,31,4003,37,America/Sao_Paulo
4,1500107,Abaetetuba,-1.72183,-48.8788,0,15,401,91,America/Sao_Paulo

## Juntando os datasets

In [9]:
dfMerged = pd.merge(dfMunicipios, dfEstados, left_on='codigo_uf', right_on='codigo_uf')
dfMerged

,codigo_ibge,nome_x,latitude_x,longitude_x,capital,codigo_uf,siafi_id,ddd,fuso_horario,uf,nome_y,latitude_y,longitude_y,regiao
0,5200050,Abadia de Goiás,-16.7573,-49.4412,0,52,1050,62,America/Sao_Paulo,GO,Goiás,-15.98,-49.86,Centro-Oeste
1,5200100,Abadiânia,-16.1970,-48.7057,0,52,9201,62,America/Sao_Paulo,GO,Goiás,-15.98,-49.86,Centro-Oeste
2,5200134,Acreúna,-17.3960,-50.3749,0,52,9645,64,America/Sao_Paulo,GO,Goiás,-15.98,-49.86,Centro-Oeste
3,5200159,Adelândia,-16.4127,-50.1657,0,52,9769,64,America/Sao_Paulo,GO,Goiás,-15.98,-49.86,Centro-Oeste
4,5200175,Água Fria de Goiás,-14.9778,-47.7823,0,52,9771,62,America/Sao_Paulo,GO,Goiás,-15.98,-49.86,Centro-Oeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,3306107,Valença,-22.2445,-43.7129,0,33,5921,24,America/Sao_Paulo,RJ,Rio de Janeiro,-22.25,-42.66,Sudeste
5566,3306156,Varre-Sai,-20.9276,-41.8701,0,33,2917,22,America/Sao_Paulo,RJ,Rio de Janeiro,-22.25,-42.66,Sudeste
5567,3306206,Vassouras,-22.4059,-43.6686,0,33,5923,24,America/Sao_Paulo,RJ,Rio de Janeiro,-22.25,-42.66,Sudeste
5568,3306305,Volta Redonda,-22.5202,-44.0996,0,33,5925,24,America/Sao_Paulo,RJ,Rio de Janeiro,-22.25,-42.66,Sudeste
5569,5300108,Brasília,-15.7795,-47.9297,1,53,9701,61,America/Sao_Paulo,DF,Distrito Federal,-15.83,-47.86,Centro-Oeste

# Minio
Cliente para conectar o Minio

In [10]:
client = boto3.client('s3', 
    endpoint_url='http://awari-minio-nginx:9000',
    aws_access_key_id='juRzyBWTAXfcT8ih',
    aws_secret_access_key='si30fZ9CPBfLPsS1r8xrRRG6aG93OS8F',
    aws_session_token=None,
    config=boto3.session.Config(signature_version='s3v4'),
    verify=False,
    region_name='sa-east-1'
)

## Salvando os data sest organizando por pastas no Minio

In [12]:
dfMerged = dfMerged.fillna("-") # Nós precisamos atrelar o resultado a variavel principal
estados = dfMerged['uf'].drop_duplicates()
estados

0       GO
246     MG
1099    PA
1243    CE
1427    BA
1844    PR
2243    SC
2538    PE
2723    TO
2862    MA
3079    RN
3246    PI
3470    RS
3967    MT
4108    AC
4130    SP
4775    ES
4853    PB
5076    AL
5178    MS
5257    RO
5309    RR
5324    AM
5386    AP
5402    SE
5477    RJ
5569    DF
Name: uf, dtype: object

In [20]:
for row in estados:
    df_por_estados = dfMerged.query("uf == '" + row + "'")
    
    if row == "-":
        folder_name = 'empty'
    else:
        folder_name = row
        
    csv_buffer = StringIO()    
    csv = df_por_estados.to_csv(csv_buffer)
    client.put_object(Body=csv_buffer.getvalue(), Bucket='aula-06', Key=f'tarefa/{folder_name}/{folder_name}.csv')

# MongoDB
Cliente para conectar o MongoDB

In [21]:
client_mongodb =  MongoClient("mongodb://root:rootpassword@awari-mongodb:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256")
db = client_mongodb['tarefa']

## Exportando os dados para o MongoDB

In [42]:
# Obter a lista de UFs a partir dos prefixos no bucket
ufs = []
objects = client.list_objects(Bucket='aula-06', Prefix='tarefa/')

for obj in objects['Contents']:
    uf = obj['Key'].split('/')[1]  # Dividir o nome do objeto por '/' e pegar o segundo elemento
    if uf not in ufs and uf != 'cidades.csv':
        ufs.append(uf)

print(ufs)

['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO']

In [45]:
# Carregar o dataset para cada estado e salvar no MongoDB
for uf in ufs:
    obj = client.get_object(
        Bucket='aula-06', 
        Key=f"tarefa/{uf}/{uf}.csv"
    ).get("Body")c

    data = pd.read_csv(obj)
    data.reset_index(inplace=True)
    data_dict = data.to_dict("records")
    
    # Criar a coleção para o estado atual e inserir os dados
    collection = db[uf]
    collection.insert_many(data_dict)

## Acessando os dados a partir do banco de dados.

In [56]:
# Removendo colunas inuteis
collection.update_many({}, {'$unset': {'index': "", 'Unnamed: 0': ""}})

# Visualizando os dados para o estado de SP, por exemplo
cidadesPorUF = collection.find({"uf":"SP"})
dfCidadesPorUF = pd.DataFrame(list(cidadesPorUF))

dfCidadesPorUF

,_id,codigo_ibge,nome_x,latitude_x,longitude_x,capital,codigo_uf,siafi_id,ddd,fuso_horario,uf,nome_y,latitude_y,longitude_y,regiao
0,649886fc5dddc04386ebffdf,3500105,Adamantina,-21.6820,-51.0737,0,35,6101,18,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
1,649886fc5dddc04386ebffe0,3500204,Adolfo,-21.2325,-49.6451,0,35,6103,17,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
2,649886fc5dddc04386ebffe1,3500303,Aguaí,-22.0572,-46.9735,0,35,6105,19,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
3,649886fc5dddc04386ebffe2,3500402,Águas da Prata,-21.9319,-46.7176,0,35,6107,19,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
4,649886fc5dddc04386ebffe3,3500501,Águas de Lindóia,-22.4733,-46.6314,0,35,6109,19,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,649886fc5dddc04386ec025f,3556909,Vista Alegre do Alto,-21.1692,-48.6284,0,35,7241,16,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
641,649886fc5dddc04386ec0260,3556958,Vitória Brasil,-20.1956,-50.4875,0,35,828,17,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
642,649886fc5dddc04386ec0261,3557006,Votorantim,-23.5446,-47.4388,0,35,7243,15,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
643,649886fc5dddc04386ec0262,3557105,Votuporanga,-20.4237,-49.9781,0,35,7245,17,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste
644,649886fc5dddc04386ec0263,3557154,Zacarias,-21.0506,-50.0552,0,35,2973,18,America/Sao_Paulo,SP,São Paulo,-22.19,-48.79,Sudeste

---

Notebook utilizado para fins educacionais da **Awari**.

**© AWARI. Todos os direitos reservados.**